### ISSUE TITLE
Not Workin On Android 8.0

### ISSUE THREAD

**Issue by FasdAR** [AndreasHennig/ProgressRingPlugin#7]
I get the usual progressbar instead of a circle.

![photo_2018-02-04_16-41-41](https://user-images.githubusercontent.com/23176494/35778110-7d5a2de2-09ca-11e8-9f60-a791881c6c4c.jpg)
`

![default](https://user-images.githubusercontent.com/23176494/35778114-86dc7bae-09ca-11e8-92e5-4026dd09975a.PNG)

**Comment by Nevyn75** [comment]
Up.

Same problem for me...
Very nice and easy to use control, is it possible to have it fixed? 

Thx

**Comment by AndreasHennig** [comment]
Hi,
hm...wasn't able to reproduce the issue. I know that this error happens if you forget to also install the ProgressRing package in the Android project but I guess that's not the case? Oh and which Xamarin.Forms version are you using?

**Comment by Nevyn75** [comment]
Oh my God...
You're right! After last Xamarin/Visual Studio update my csproj file was completely messed up... I guess I lost the plugin dependency into Android project!

Sorry for the false alarm and thank you very much for your support.

Best regards.

**Comment by FasdAR** [comment]
Hi, sorry for the long answer, it was not possible to answer before, the
error occurred on devices above androyd 6.0, at that time the version of
xamarin forms was the last, corrected this error very easily, by writing
its controller

пн, 9 апр. 2018 г., 0:26 Nevyn75 <notifications@github.com>:

**Comment by AndreasHennig** [comment]
> You're right! After last Xamarin/Visual Studio update my csproj file was completely messed up... I guess I lost the plugin dependency into Android project!
> 
> Sorry for the false alarm and thank you very much for your support.
You're welcome :) Now that your problem is solved I'll just close this issue. Feel free to ask if you have any others questions.
